<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testResult type="org.overture.typechecker.tests.external.ExternalClassesPpTypeCheckTest">
<message column="14" line="28" message="Cannot use 'new' in a functional context" messageType="error" number="3348" resource="overload-11.vpp"/>
<message column="3" line="28" message="Cannot use 'new' in a functional context" messageType="error" number="3348" resource="overload-11.vpp"/>
<message column="11" line="28" message="Inaccessible member fn(A) of class A" messageType="error" number="3092" resource="overload-11.vpp"/>
<message column="6" line="38" message="Cannot use 'new' in a functional context" messageType="error" number="3348" resource="overload-11.vpp"/>
<message column="3" line="38" message="Name 'fn(A)' is not in scope" messageType="error" number="3182" resource="overload-11.vpp"/>
<message column="6" line="42" message="Cannot use 'new' in a functional context" messageType="error" number="3348" resource="overload-11.vpp"/>
<result/>
</testResult>
